#ifndef FORWARD_RENDERING_TASK_MESH_SHADER_INTERFACE_GLSL
#define FORWARD_RENDERING_TASK_MESH_SHADER_INTERFACE_GLSL

#ifndef USE_MESHOPTIMIZER_STYLE_RENDERER
#define NUM_EXTRACTION_BLOCK 32
#define NUM_MESHLETS_TO_CHECK 1024 // up to 32 meshlets per block, and 32 threads at once
uint32_t absoluteIDs[NUM_MESHLETS_TO_CHECK];
#else //MESHOPT_STYLE_RENDERER
#define NUM_MESHLETS_TO_CHECK 32 // up to 32 meshlets per block, and 32 threads at once
uint32_t baseID;
uint8_t baseIDOffset[NUM_MESHLETS_TO_CHECK];
#endif //MESHOPT_STYLE_RENDERER


#endif //FORWARD_RENDERING__TASK_MESH_SHADER_INTERFACE_GLSL